services:
  mongo:
    profiles:
      - db
    hostname: mongo
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DBUSERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DBPASSWORD}
    volumes:
      - ./container/db:/data/db
    networks:
      - gargoyle
    ports:
      - 27017:27017

networks:
  gargoyle:
    driver: bridge