services:
  app:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    profiles:
      - app
    volumes:
      - .:/workspace/gargoyle
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      PREFIX: ','
      MONGO_URI: ${MONGO_URI}
      STEAM_API: ${STEAM_API}
      SUGGESTION_CHANNEL_ID: ${SUGGESTION_CHANNEL_ID}
      CERSH_API_KEY: ${CERSH_API_KEY}
      DEBUG_LEVEL: 6
      LOG_TO_FILE: false
      PROXMOX_NOTIFY_AUTH: ${PROXMOX_NOTIFY_AUTH}
      PROXMOX_NOTIFY_CHANNEL_ID: ${PROXMOX_NOTIFY_CHANNEL_ID}
      FINNHUB_API_KEY: ${FINNHUB_API_KEY}
      BGN_STAFF_DB_HOST: ${BGN_STAFF_DB_HOST}
      BGN_STAFF_DB_USER: ${BGN_STAFF_DB_USER}
      BGN_STAFF_DB_PASS: ${BGN_STAFF_DB_PASS}
      BGN_STAFF_DB_NAME: ${BGN_STAFF_DB_NAME}
      BGN_ADMIN_DB_USER: ${BGN_ADMIN_DB_USER}
      BGN_ADMIN_DB_PASS: ${BGN_ADMIN_DB_PASS}
      BGN_API_KEY: ${BGN_API_KEY}
      EXTERNAL_MODULES: ${EXTERNAL_MODULES}

    ports:
      - 3001:3001
    networks:
      - gargoyle

  mongo:
    hostname: mongo
    image: mongo:latest
    ports:
      - 27017:27017
    profiles:
      - aux
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DBUSERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DBPASSWORD}
    volumes:
      - ./container/db:/data/db
      - ./container/configdb:/data/configdb
    networks:
      - gargoyle

networks:
  gargoyle:
    driver: bridge
